
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sistema.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int interrogacionabre = 26;
  public static final int corchetecierra = 25;
  public static final int suma = 31;
  public static final int puntos = 18;
  public static final int resta = 32;
  public static final int llaveabre = 21;
  public static final int coma = 28;
  public static final int igual = 19;
  public static final int identificador = 35;
  public static final int definirglobales = 2;
  public static final int multiplicacion = 33;
  public static final int definirxyline = 14;
  public static final int puntoycoma = 20;
  public static final int numero = 39;
  public static final int interrogacioncierra = 27;
  public static final int graficalineas = 6;
  public static final int EOF = 0;
  public static final int corcheteabre = 24;
  public static final int nombre = 15;
  public static final int error = 1;
  public static final int color = 16;
  public static final int parentesisabre = 29;
  public static final int entero = 3;
  public static final int str = 4;
  public static final int dospuntos = 23;
  public static final int graficabarras = 5;
  public static final int id = 38;
  public static final int parentesiscierra = 30;
  public static final int galeria = 7;
  public static final int tituloy = 10;
  public static final int titulox = 9;
  public static final int llavecierra = 22;
  public static final int titulo = 8;
  public static final int grosor = 17;
  public static final int puntosxy = 13;
  public static final int aceptacion = 37;
  public static final int division = 34;
  public static final int ejey = 12;
  public static final int ejex = 11;
  public static final int cadena = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "definirglobales",
  "entero",
  "str",
  "graficabarras",
  "graficalineas",
  "galeria",
  "titulo",
  "titulox",
  "tituloy",
  "ejex",
  "ejey",
  "puntosxy",
  "definirxyline",
  "nombre",
  "color",
  "grosor",
  "puntos",
  "igual",
  "puntoycoma",
  "llaveabre",
  "llavecierra",
  "dospuntos",
  "corcheteabre",
  "corchetecierra",
  "interrogacionabre",
  "interrogacioncierra",
  "coma",
  "parentesisabre",
  "parentesiscierra",
  "suma",
  "resta",
  "multiplicacion",
  "division",
  "identificador",
  "cadena",
  "aceptacion",
  "id",
  "numero"
  };
}

